apiVersion: v1
data:
  mapRoles: | 
    - groups:
      - system:masters
      rolearn: arn:aws:iam::130433542042:role/UdacityFlaskDeployCBKubectlRole
      username: build 
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::130433542042:role/eksctl-eksctl-demo-nodegroup-ng-c-NodeInstanceRole-E451K8WN29FH
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-17T22:23:48Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1650"
  uid: 4a320a01-33ad-4631-9f67-21ef1c597f69
